language: generic

services:
  - docker

before_install:
  - ./run gcloud-config
  - ./run gcloud-activate-service-account

jobs:
  include:
    - stage: Build
      script: ./run build
    - stage: Test
      script: ./run test
    - stage: Deploy
      script: ./run deploy
    - stage: Release
      script: ./run release

stages:
  - Build
  - Test
  - name: Deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
  - name: Release
    if: (NOT type IN (pull_request)) AND (branch = master)
