#!/bin/bash

set -euo pipefail

source .convenience/source "v0.8.1"

GIT_ORG=ssttuu
GIT_REPO=go-bench-report
IMAGE_HOST="gcr.io"
IMAGE_REPO="${IMAGE_HOST}/i-m-a-g-e-s"
IMAGE_NAME="go-bench-report"

export GO111MODULE=on

function build() {
    docker-build $(githash-short)
    docker-push $(githash-short)
}

function docker-login-with-json-key() {
    docker login -u _json_key --password-stdin https://${IMAGE_HOST}
}

function test() {
    echo "TODO"
}

function deploy() {
    docker-pull $(githash-short)
    docker-tag $(githash-short) $(get-tags)
    docker-push
}

function release() {
    git-tag
    git-tag-push
    git-release <<EOF
{
  "tag_name": "$(get-version)",
  "target_commitish": "master",
  "name": "$(get-version)",
  "body": "$(get-version)",
  "draft": false,
  "prerelease": false
}
EOF
}

"$@"
