#!/bin/bash

set -euo pipefail

source .convenience/source "v0.7.1"

GIT_ORG=ssttuu
GIT_REPO=go-bench-report
IMAGE_REPO=gcr.io/i-m-a-g-e-s
IMAGE_NAME=go-bench-report

export GO111MODULE=on

function build() {
    docker-build
}

function test() {
    echo "TODO"
}

function deploy() {
    # TODO: do not rebuild before deploying
    docker-build
    docker-push
}

function release() {
    git-tag
    git-tag-push
    git-release <<EOF
{
  "tag_name": "$(get-version)",
  "target_commitish": "master",
  "name": "$(get-version)",
  "body": "$(get-version)",
  "draft": false,
  "prerelease": false
}
EOF
}

"$@"
